localization:

  image: ubuntu:noble

  only:
    - schedules

  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y qt6-base-dev qt6-l10n-tools openssh-client git wget python3-minimal python3-ruamel.yaml
    - git config --global user.email "Lukas@photoqt.org"
    - git config --global user.name "Lukas Spies"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/lspies/photoqt-extensions-lang.git && cd photoqt-extensions-lang
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../CropImage -ts CropImage.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../ExportImage -ts ExportImage.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../FloatingNavigation -ts FloatingNavigation.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../Histogram -ts Histogram.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../ImgurCom -ts ImgurCom.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../MapCurrent -ts MapCurrent.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../QuickActions -ts QuickActions.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../ScaleImage -ts ScaleImage.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../Wallpaper -ts Wallpaper.ts
    - /usr/lib/qt6/bin/lupdate -no-obsolete ../ThumbnailGenerator -ts ThumbnailGenerator.ts
    - python3 generate_manifests_for_translation.py
    - git add CropImage.ts CropImage_manifest.yml
    - git add ExportImage.ts ExportImage_manifest.yml
    - git add FloatingNavigation.ts FloatingNavigation_manifest.yml
    - git add Histogram.ts Histogram_manifest.yml
    - git add ImgurCom.ts ImgurCom_manifest.yml
    - git add MapCurrent.ts MapCurrent_manifest.yml
    - git add QuickActions.ts QuickActions_manifest.yml
    - git add ScaleImage.ts ScaleImage_manifest.yml
    - git add Wallpaper.ts Wallpaper_manifest.yml
    - git add ThumbnailGenerator.ts ThumbnailGenerator_manifest.yml
    - git diff-index --quiet HEAD || git commit -m "updating translation source files from CI"
    - git push origin main
