function(PQINSTALL)

    #########################################################################
    file(COPY_FILE definition.yml ${CMAKE_BINARY_DIR}/extensions/${PROJECT_NAME}/definition.yml)

    #########################################################################
    # HERE WE PROCESS AND COPY THE QML FILES TO THE CURRENT WORKING TREE

    file(GLOB qmlfiles "qml/*qml")
    foreach(QMLFILE ${qmlfiles})

        # a change to any of these files triggers cmake rerun
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${QMLFILE}")

        # get relative dir without qml/ prefix
        file(RELATIVE_PATH GENERICPATH "${CMAKE_CURRENT_SOURCE_DIR}/qml" "${QMLFILE}")

        # the two target filenames
        set(FILENAME_MODERN "${CMAKE_BINARY_DIR}/extensions/${PROJECT_NAME}/qml/modern/${GENERICPATH}")
        set(FILENAME_INTEGRATED "${CMAKE_BINARY_DIR}/extensions/${PROJECT_NAME}/qml/integrated/${GENERICPATH}")

        # if the source file has been updated
        if("${QMLFILE}" IS_NEWER_THAN "${FILENAME_MODERN}" OR "${QMLFILE}" IS_NEWER_THAN "${FILENAME_INTEGRATED}")

            # create two copies of the files with the two different imports
            file(READ "${QMLFILE}" FILE_CONTENTS)

            set(TXT_NOTE "/****************************************************/
    /*                                                  */
    /*                                                  */
    /*              DO NOT EDIT THIS FILE!              */
    /*                                                  */
    /*                                                  */
    /****************************************************/
    ")

            string(REPLACE "import PhotoQt\n" "import PhotoQt.Modern\n\n${TXT_NOTE}\n" FILE_CONTENTS_MODERN "${FILE_CONTENTS}")
            file(WRITE "${FILENAME_MODERN}" "${FILE_CONTENTS_MODERN}")

            string(REPLACE "import PhotoQt\n" "import PhotoQt.Integrated\n\n${TXT_NOTE}\n" FILE_CONTENTS_INTEGRATED "${FILE_CONTENTS}")
            file(WRITE "${FILENAME_INTEGRATED}" "${FILE_CONTENTS_INTEGRATED}")

        endif()

        install(FILES qml/.generated/modern/${GENERICPATH} DESTINATION lib/PhotoQt/extensions/${PROJECT_NAME}/qml/modern/)
        install(FILES qml/.generated/integrated/${GENERICPATH} DESTINATION lib/PhotoQt/extensions/${PROJECT_NAME}/qml/integrated/)

    endforeach()

endfunction()
